### ISSUE TITLE
[MORPHOLOGY] Adverbs ending with -mente

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/portuguese-pos-dict#37]
Heya, @p-goulart ,

I was going to add the morphologic information for the words I added yesterday, and I wanted to start with the -mente adverbs, so I found this file:
adv_mente-lt.txt

However, it has the words as RG instead of RM.

But the text analysis on the website seems to show them as RM (which is the correct tag?):
https://community.languagetool.org/analysis/index?lang=pt

Take for example this word:
`topograficamente`
I was going to add it, but it was already in the .txt tagged as RG, but it appears as RM which I believe it is the correct.

How do I add them?

Thanks!

**Comment by p-goulart** [comment]
You can add them to the `adv_mente-lt.txt` file without a problem, as either `RG` or `RM`, and they will be converted to `RM`.

You are correct that those are supposed to be `RM`.

---

The way this currently works is the Portuguese tagger tags *-mente*-suffixed adverbs with as `RG`, and then there is a disambiguator rule to turn those into `RM`. I don't know why it's done this way, it seems silly.

We *could* fix this so that these adverbs are `RM` from the start, of course, but I don't think our rules really *need* the `RG` vs. `RM` distinction anyway..? Anyway, yeah, it's safe to add them there.

**Comment by marcoagpinto** [comment]
Thanks for explaining!
